apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate-job
spec:
  backoffLimit: 4
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      containers:
        - name: django-migrate
          image: lypavel/django_app:latest
          imagePullPolicy: IfNotPresent
          command: ['python', 'manage.py', 'migrate', '--noinput']
          envFrom:
            - secretRef:
                name: django-secrets
            - configMapRef:
                name: django-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: dsn
      restartPolicy: OnFailure
