apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions-cronjob
spec:
  schedule: '0 0 7,14,21,28 * *'
  startingDeadlineSeconds: 360
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
            - name: clearsessions
              image: lypavel/django_app:latest
              command: ['python', 'manage.py', 'clearsessions']
              imagePullPolicy: IfNotPresent
              envFrom:
                - secretRef:
                    name: django-secrets
                - configMapRef:
                    name: django-config
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: postgres
                      key: dsn
          restartPolicy: OnFailure
      backoffLimit: 4
